server:
  port: 8091
eureka:
  client:
    service-url:
      default-Zone: http://127.0.0.1:8761/eureka/
spring:
  application:
    name: usian-item-web
fdfs:
  so-timeout: 1501 # 超时时间
  connect-timeout: 601 # 连接超时时间
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: 192.168.157.136:22122  # tracker地址：你的虚拟机服务器地址+端口（默认是22122）