server:
  port: 8090
eureka:
  client:
    service-url:
      default-Zone: http://127.0.0.1:8761/eureka/
spring:
  application:
    name: usian-item-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/usian?characterEncoding=UTF-8
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    cluster:
      nodes:
        - 192.168.157.137:7001
        - 192.168.157.137:7002
        - 192.168.157.137:7003
        - 192.168.157.137:7004
        - 192.168.157.137:7005
        - 192.168.157.137:7006
    jedis:
      pool:
        max-active: 20 #连接池最大连接数
        max-idle: 10 #连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接

#配置缓存首页商品分类的 key
portal_catresult_redis_key: portal_catresult_redis_key

#配置缓存商品信息的key
portal_itemresult_redis_key: portal_itemresult_redis_key
